feature #7: persist settings
TheTanic/Semoda pull request #19
Opened 2024-08-08 16:55 UTC by Ploinky

Here is a suggestion on how this may be implemented. It saves settings in a `appsettings.json` right next to the executable of the application, currently only a simple string for language since no settings have actually been implemented in the application.

If no settings file is found on startup, default settings can are used. These can then be changed and/or saved to a new `appsettings.json`.

This version of the feature uses [Microsoft.Extensions.Configuration](https://www.nuget.org/packages/Microsoft.Extensions.Configuration) to load the configuration file. This is slightly overkilly for the simple json file case, but leaves room to later load from environment variables or other (custom) sources.

The Microsoft package does not offer any functionality for saving settings, so they are simply json-serialized and written to the local file system using standard C# functions.

The `AppSettingsModel` offers a `PropertyChangedEventHandler` that can be used to react to settings changes.

The model can be dependency injected, such as:

```
public DashboardPageViewModel(AppSettingsModel appSettings) : base(true)
{
    Debug.WriteLine("Current app language: " + appSettings.Language);
}
```

2024-08-08 17:28 UTC, TheTanic requested changes

2024-08-08 17:28 UTC, TheTanic commented on src/Semoda/Semoda/Extensions/ServiceCollectionExtensions.cs
> +                collection.AddSingleton(appSettings);
Instead uf adding a custom app mode, we should add the IConfiguration to our application. So we are able to seperate the settings in multiple

2024-08-08 17:28 UTC, TheTanic commented on src/Semoda/Semoda/Extensions/ServiceCollectionExtensions.cs
> +                   .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
Use a constant for the file name.

2024-08-08 17:28 UTC, TheTanic commented on src/Semoda/Semoda/Extensions/ServiceCollectionExtensions.cs
> +                   .SetBasePath(Directory.GetCurrentDirectory())
We should move the configuration path to a different location. To make it less easy to manipulate the file. Maybe the ApplicationData is a good location?

2024-08-08 17:28 UTC, TheTanic commented on src/Semoda/Semoda/Models/AppSettingsModel.cs
> +    public class AppSettingsModel : INotifyPropertyChanged
Instead of using the INotifyPropertyChanged interface, the ObservableObject of the MVVM Toolkit should be used.

2024-08-08 17:28 UTC, TheTanic commented on src/Semoda/Semoda/Models/AppSettingsModel.cs
> +        public event PropertyChangedEventHandler? PropertyChanged;
Not needed when using the MVVM Toolkit

2024-08-08 17:28 UTC, TheTanic commented on src/Semoda/Semoda/Models/AppSettingsModel.cs
> +        protected void OnPropertyChanged([CallerMemberName] string propertyName = null)
Not needed when using the MVVM Toolkit

2024-08-08 17:28 UTC, TheTanic commented on src/Semoda/Semoda/Models/AppSettingsModel.cs
> +        public string Language
Use a ObservableProperty instead

2024-08-08 17:28 UTC, TheTanic commented on src/Semoda/Semoda/Models/AppSettingsModel.cs
> +        public void Save()
A Model should not be responsible for saving data. It just holds data. Outsource this to a service

2024-08-08 19:22 UTC, TheTanic commented on src/Semoda/Semoda/Services/ConfigService.cs
> +				File.WriteAllText("appsettings.json", JsonSerializer.Serialize(new AppSettingsModel(), new JsonSerializerOptions { WriteIndented = true }));
Magic string --> Change to constant

2024-08-08 19:22 UTC, TheTanic commented on src/Semoda/Semoda/Services/ConfigService.cs
> +			if(!File.Exists("appsettings.json"))
Change path

2024-08-08 19:22 UTC, TheTanic commented on src/Semoda/Semoda/ViewModels/SettingsPageViewModel.cs
> +            AppSettingsModel.Language = "de";
Remove this in final commit

2024-08-08 19:24 UTC, TheTanic requested changes
Filepath and names should be handled

2024-08-09 10:17 UTC, TheTanic requested changes

2024-08-09 19:35 UTC, Ploinky commented on src/Semoda/Semoda/Services/ConfigService.cs
> +		private const string SettingsFolderName = "Semoda";
Apparently we can, but we have to make it `readonly static` instead of `const`.

2024-08-09 19:38 UTC, Ploinky commented on src/Semoda/Semoda/Services/ConfigService.cs
> +		public bool Update(AppSettingsModel newSettings)
it looked fine for me, what am i missing?

2024-08-09 19:43 UTC, TheTanic commented on src/Semoda/Semoda/Services/ConfigService.cs
> +		private const string SettingsFolderName = "Semoda";
Static read-only is fine for me

2024-08-09 19:44 UTC, TheTanic approved these changes

2024-08-09 19:45 UTC, merged